# 配置文件的版本
version: "3.8"
# 服务器群
services:
  # 网页服务
  django:
    restart: always
    build: .
    # 在数据库搭建完成之后启动
    depends_on:
      - mysql
    ports:
      - 8000:8000
    # 运行命令
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
  # 数据库服务
  mysql:
    # 用当前文件夹的Dockerfile来构建
    image: mysql
    restart: always
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE : "django_hello"
      MYSQL_ROOT_PASSWORD : 123456