# Generated by Django 4.1.1 on 2022-10-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='loc',
            field=models.CharField(default='', max_length=20),
        ),
    ]
